#!/bin/bash

set -e

usage() {
    cat <<EOF
USAGE: $(basename "$0") [-hf] subcommand [options ...]
OPTIONS:
  -h        | help
SUBCOMMANDS:
  b|backup [<app...>]      | create adb backup
  l|list <backup>          | list apps in adb backup
  i|installed [-3] [-f]    | list installed apps
  p|pack <app>             | pack app into adb backup
  r|restore <backup> <app> | restore app in adb backup
  p|unpack <backup> <app>  | unpack app in adb backup
EOF
    exit 1
}

backup() {
    if [ -n "$1" ]
    then
        app=$*
        backup="${app// /_}.ab"
    else
        app="-all"
        backup="$(date +%Y-%m-%d).ab"
    fi
    adb -d backup -f "$backup" -apk $app
}

list() {
    backup="$1"
    test -z "$backup" && usage
    backup_list="list/$backup.list"
    mkdir -p list
    if [ "$backup" -nt "$backup_list" ]
    then
        tail -n +5 "$backup" \
            | zlib-flate -uncompress \
            | tar -tf - \
            | awk -F/ '{print $2}' \
            | uniq \
            | tee "$backup_list"
    else
        cat "$backup_list"
    fi
}

installed() {
    adb -d shell cmd package list packages "$@" | sed 's/^package://'
}

pack() {
    mkdir -p pack
    app="$1"
    test -z "$app" && usage
    app="${app/#apps\//}"
    (echo -ne 'ANDROID BACKUP\n1\n1\nnone\n' && tar --format=ustar -cf - "apps/$app" | zlib-flate -compress) >"pack/$app.ab"
}

restore() {
    backup="$1"
    app="$2"
    test -z "$backup" && usage
    test -z "$app" && usage
    unpack "$backup" "$app"
    pack "$app"
    adb -d install "apps/$app/a/base.apk" || true
    adb -d restore "pack/$app.ab"
}

unpack() {
    backup="$1"
    app="$2"
    test -z "$backup" && usage
    tail -n +5 "$backup" | zlib-flate -uncompress | tar -xf - "apps/$app"
}

action="$1"
case "$action" in
    b) action=backup ;;
    l) action=list ;;
    i) action=installed ;;
    p) action=pack ;;
    r) action=restore ;;
    u) action=unpack ;;
esac

if type "$action" 2>/dev/null | grep -qF "function"
then
    shift
    $action "$@"
else
    usage
fi
