#!/bin/bash

# apt-get install adb qpdf rsync

set -e

ADB='adb -d'
ABR_DIR="$(dirname "$(readlink -f "$0")")"
RAW_BACKUP_DIR="raw_backup"
RSYNC_LOCAL_PORT='1873'
RSYNC_BASE_PATH="rsync://backup@127.0.0.1:${RSYNC_LOCAL_PORT}"

usage() {
    cat <<EOF
USAGE: $(basename "$0") [-hf] subcommand [options ...]
OPTIONS:
  -h        | help
SUBCOMMANDS:
  ab|adb_backup [<app...>]      | create adb backup
  d|diff <backup>               | diff apps from installed to backup
  al|adb_list <backup>          | list apps in adb backup
  i|installed [-3] [-f]         | list installed apps
  ap|adb_pack <app>             | pack app into adb backup
  ar|adb_restore <backup> <app> | restore app in adb backup
  rb|raw_backup <app>           | backup app by raw files
  rr|raw_restore <app>          | restore app by raw files
  p|unpack <backup> <app>       | unpack app in adb backup
EOF
    exit 1
}

appops_set_ignore () {
    app="$1"
    test -z "$app" && usage
    for op in $($ADB shell cmd appops get "$app" | awk -F: '{print $1}' | grep -Fv READ_CALENDAR || true)
    do
        $ADB shell cmd appops set "$app" "$op" ignore
    done
}

adb_backup() {
    if [ -n "$1" ]
    then
        app=$*
        backup="${app// /_}.ab"
    else
        app="-all"
        backup="$(date +%Y-%m-%d).ab"
    fi
    $ADB backup -f "$backup" -apk $app
}

appops_backup() {
    app="$1"
    test -z "$app" && usage
    mkdir -p appops
    appops="$($ADB shell cmd appops get "$app" | awk -F ' +|:|;' '{ if($3=="ignore" || $3=="allow") {print $1,$3} }' | grep -Fv READ_CALENDAR || true)"
    if [ -n "$appops" ]
    then
        if [ -d "$RAW_BACKUP_DIR/$app" ]
        then
            echo "$appops" >"$RAW_BACKUP_DIR/$app/appops"
        fi
        echo "$appops" >"appops/$app"
    fi
}

appops_backup_all() {
    for app in $(installed -3)
    do
        appops_backup "$app"
    done
}

diff() {
    backup="$1"
    test -z "$backup" && usage
    command diff -u <(installed -3 | sort) <(list "$backup" | sort)
}

adb_list() {
    backup="$1"
    test -z "$backup" && usage
    backup_list="list/$backup.list"
    mkdir -p list
    if [ "$backup" -nt "$backup_list" ]
    then
        tail -n +5 "$backup" \
            | zlib-flate -uncompress \
            | tar -tf - \
            | awk -F/ '{print $2}' \
            | uniq \
            | tee "$backup_list"
    else
        cat "$backup_list"
    fi
}

installed() {
    if $ADB shell cmd | grep -q 'cmd: not found'; then
        $ADB shell pm list packages "$@" | sed 's/^package://'
    else
        $ADB shell cmd package list packages "$@" | sed 's/^package://'
    fi
}

adb_pack() {
    mkdir -p pack
    app="$1"
    test -z "$app" && usage
    app="${app/#apps\//}"
    (echo -ne 'ANDROID BACKUP\n1\n1\nnone\n' && tar --format=ustar -cf - -T "apps/$app.list" | zlib-flate -compress) >"pack/$app.ab"
}

adb_restore() {
    backup="$1"
    app="$2"
    test -z "$backup" && usage
    test -z "$app" && usage
    unpack "$backup" "$app"
    adb_pack "$app"
    $ADB install "apps/$app/a/base.apk" || true
    $ADB restore "pack/$app.ab"
    appops_restore "$app"
}

appops_restore {
    app="$1"
    test -z "$app" && usage
    if [ -d "$RAW_BACKUP_DIR/$app" ]
    then
        appops_file="$RAW_BACKUP_DIR/$app/appops"
    else
        appops_file=appops/$app
    fi
    if [ ! -f "$appops_file" ]
    then
        echo "appops file not exists."
        return
    fi
    while read -r op mode
    do
        $ADB shell -n cmd appops set "$app" "$op" "$mode"
    done < "$appops_file"
}

adb_root() {
    $ADB wait-for-device
    if [ "$($ADB shell whoami)" != 'root' ]
    then
        if [ "$($ADB shell getprop ro.adb.secure)" = 0 ]
        then
            $ADB root
        else
            $ADB shell 'su -c "stop adbd && setprop service.adb.root 1 && start adbd"'
        fi
        $ADB wait-for-device
    fi
}

adb_unroot() {
    $ADB wait-for-device
    if [ "$($ADB shell whoami)" = 'root' ]
    then
        if [ "$($ADB shell getprop ro.adb.secure)" = 0 ]
        then
            $ADB unroot
        else
            $ADB shell 'su -c "stop adbd && setprop service.adb.root 0 && start adbd"'
        fi
        $ADB wait-for-device
    fi
}

captive_portal() {
    $ADB shell settings put global captive_portal_server google.cn
    $ADB shell settings put global captive_portal_http_url http://google.cn/generate_204
    $ADB shell settings put global captive_portal_https_url https://google.cn/generate_204
}

start_rsync() {
    adb_root
    if ! adb shell test -e /mnt/secure/rsyncd.pid
    then
        $ADB shell 'cat >/mnt/secure/rsyncd.conf' <<EOF
address = 127.0.0.1
gid = root
pid file = /mnt/secure/rsyncd.pid
read only = false
uid = root
use chroot = false
[data]
  auth users = backup
  hosts allow = 127.0.0.1
  path = /data
  secrets file = /mnt/secure/rsyncd.secrets
EOF
        password="$(LC_ALL=C tr -dc '[:graph:]' < /dev/urandom | head -c 16)"
        $ADB shell 'cat >/mnt/secure/rsyncd.secrets' <<EOF
backup:${password}
EOF
        $ADB shell chmod 600 /mnt/secure/rsyncd.conf /mnt/secure/rsyncd.secrets
        $ADB shell -t rsync --daemon --config=/mnt/secure/rsyncd.conf
    fi
    adb forward "tcp:$RSYNC_LOCAL_PORT" tcp:873
}

stop_rsync() {
    if adb shell test -e /mnt/secure/rsyncd.pid
    then
        $ADB shell 'kill $(cat /mnt/secure/rsyncd.pid)'
    fi
    $ADB shell rm /mnt/secure/rsyncd.conf /mnt/secure/rsyncd.secrets || true
    $ADB forward --remove "tcp:$RSYNC_LOCAL_PORT" || true
    adb_unroot
}

raw_backup() {
    app="$1"
    test -z "$app" && usage
    start_rsync
    $ADB shell am force-stop "$app"
    mkdir -p "$RAW_BACKUP_DIR/$app"
    apk="$($ADB shell pm path "$app")"
    apk="${apk:8}"
    password="$(rsync_password)"
    RSYNC_PASSWORD="$password" rsync "${RSYNC_BASE_PATH}${apk}" "$RAW_BACKUP_DIR/$app/$app.apk"
    RSYNC_PASSWORD="$password" rsync -a --exclude="/cache/" --exclude="/code_cache/" --exclude="/lib" "${RSYNC_BASE_PATH}/data/data/$app/" "$RAW_BACKUP_DIR/$app/data/"
    appops_backup "$app"
}

raw_backup_spefial() {
    start_rsync
    mkdir -p "$RAW_BACKUP_DIR/spefial/data"
    password="$(rsync_password)"
    RSYNC_PASSWORD="$password" rsync -av --ignore-missing-args --files-from="$ABR_DIR/spefial.list" "${RSYNC_BASE_PATH}/" "$RAW_BACKUP_DIR/spefial/"
}

raw_restore() {
    app="$1"
    test -z "$app" && usage
    start_rsync
    $ADB install "$RAW_BACKUP_DIR/$app/$app.apk" || true
    $ADB shell am force-stop "$app"
    user="$($ADB shell stat -c '%U:%G' "/data/data/$app")"
    password="$(rsync_password)"
    RSYNC_PASSWORD="$password" rsync -a --chown="$user" --exclude="/cache/" --exclude="/code_cache/" --exclude="/lib" "$RAW_BACKUP_DIR/$app/data/" "${RSYNC_BASE_PATH}/data/data/$app/"
    $ADB shell restorecon -R "/data/data/$app"
    appops_restore "$app"
}

rsync_password() {
    password="$($ADB shell cat /mnt/secure/rsyncd.secrets)"
    password="${password:7}"
    echo "${password}"
}

unpack() {
    backup="$1"
    app="$2"
    test -z "$backup" && usage
    app_list="apps/$app.list"
    mkdir -p apps
    tail -n +5 "$backup" | zlib-flate -uncompress | tar -xvf - "apps/$app" > "$app_list"
}

action="$1"
case "$action" in
    ab) action=adb_backup ;;
    d) action=diff ;;
    i) action=installed ;;
    al) action=adb_list ;;
    ap) action=adb_pack ;;
    ar) action=adb_restore ;;
    rb) action=raw_backup ;;
    rr) action=raw_restore ;;
    u) action=unpack ;;
esac

if type "$action" 2>/dev/null | grep -qF "function"
then
    shift
    $action "$@"
else
    usage
fi
